# Generated by Django 4.1 on 2024-08-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varity',
            name='image',
        ),
    ]
