# Generated by Django 4.1 on 2024-08-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_varity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.varity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('varity', models.ManyToManyField(related_name='collage', to='app.varity')),
            ],
        ),
        migrations.CreateModel(
            name='cetificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_no', models.CharField(max_length=100)),
                ('issueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('validUntil', models.DateTimeField()),
                ('cer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='app.varity')),
            ],
        ),
    ]
